### ISSUE TITLE
Your code is not working

### ISSUE THREAD

**Issue by voidsteed** [SwingDev/microconf-workshops#1]
if you clone your code from repo and run yarn install and yarn start. It is not working because it is not possible to parse your scss files.

**Comment by disname** [comment]
Same issue

**Comment by jacobsturm** [comment]
Still an issue.

**Comment by witiokz** [comment]
Yea, it is true. If you want at least to build this project and see working list of notes without styling, you can use this modified webpack.dev.js
[webpack.dev.js.txt](https://github.com/SwingDev/microconf-workshops/files/3252336/webpack.dev.js.txt). You will also need to install redux, postcss-preset-env, postcss-flexbugs-fixes.

**Comment by vvishwa** [comment]
Hi,

On iMac I see problem with sudo yarn install

➤ YN0013: │ typescript@patch:typescript@npm%3A2.8.3#builtin<compat/typescript>::version=2.8.3&hash=226bd1 can't be found in the cache and will be fetched from the disk
➤ YN0001: │ Error: typescript@patch:typescript@npm%3A2.8.3#builtin<compat/typescript>::version=2.8.3&hash=226bd1: Cannot apply hunk #1
    at c (/usr/local/lib/node_modules/yarn/bin/yarn.js:58:888149)
    at process._tickCallback (internal/process/next_tick.js:68:7)
➤ YN0000: └ Completed in 10.54s
➤ YN0000: Failed with errors in 22.6s
